### PR TITLE
removing dependabot.yml

### PR DESCRIPTION
**Pull request by max-hassani**
removing dependabot.yml file, so the previous setup for updating dependencies continues to work.

### CODE REVIEW

**Comment by max-hassani** [comment]
@jan-janssen do you think it is sufficient to remove this yml file? or shall I change something in the setting as well?

**Comment by jan-janssen** [comment]
Removing should be fine - but there is still an issue with the test in the container. For supporting the latest version of `pystem` I had to change the pyiron class interfacing with the container. So I would assume that the container test did not fail because it was based on the previous version of `pystem`. But it only failed after the pull request is merged https://github.com/materialdigital/pyiron-workflow-TEMImageSegmentation/pull/6 so I have the feeling it is testing the wrong code.

**Comment by max-hassani** [comment]
> 
> 
> Removing should be fine - but there is still an issue with the test in the container. For supporting the latest version of `pystem` I had to change the pyiron class interfacing with the container. So I would assume that the container test did not fail because it was based on the previous version of `pystem`. But it only failed after the pull request is merged #6 so I have the feeling it is testing the wrong code.

I think we need to update the docker image, but let me first check locally if we update the docker image, the notebook works or not.

**Comment by max-hassani** [comment]
I checked, the notebook works fine, if we only update pystem on the docker image. I will update all the dependencies on our docker images and create a PR.

**Comment by max-hassani** [comment]
With the release of the latest docker images, the container test also passes.

**Comment by jan-janssen** [comment]
@muh-hassani that is great, but I am still a bit worried why the tests in the pull request https://github.com/materialdigital/pyiron-workflow-TEMImageSegmentation/pull/6 passed while the test on the master branch failed.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by max-hassani** [comment]
> 
> 
> @muh-hassani that is great, but I am still a bit worried why the tests in the pull request #6 passed while the test on the master branch failed.

I really don't know why it failed. Let's see what happens with this new merge.

**Pull request merged**
